// Code generated by runnerq-spec tools/gen from protocol/conductor/conductor.schema.json. DO NOT EDIT.

package protocol

// SDKInfo is the agent's SDK.
type SDKInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	// go, typescript, ...
	Language string `json:"language"`
}

// ExecutorInfo is the worker process behind a session.
type ExecutorInfo struct {
	// Stable for the process; a newer session with the same id supersedes an
	// older one.
	ID             string            `json:"id"`
	Hostname       string            `json:"hostname,omitempty"`
	Queues         []string          `json:"queues,omitempty"`
	ActivityTypes  []string          `json:"activity_types,omitempty"`
	MaxConcurrency int               `json:"max_concurrency,omitempty"`
	StartedAt      string            `json:"started_at,omitempty"`
	Labels         map[string]string `json:"labels,omitempty"`
}

// RunningActivity is an activity in flight on an executor.
type RunningActivity struct {
	ActivityID string `json:"activity_id"`
	Type       string `json:"type"`
	Attempt    int    `json:"attempt"`
	StartedAt  string `json:"started_at"`
}

// ExecutorCounters is the counts of an executor's activity outcomes since it
// started.
type ExecutorCounters struct {
	Claimed      int64 `json:"claimed"`
	Succeeded    int64 `json:"succeeded"`
	Retried      int64 `json:"retried"`
	Failed       int64 `json:"failed"`
	TimedOut     int64 `json:"timed_out"`
	DeadLettered int64 `json:"dead_lettered"`
	ClaimsLost   int64 `json:"claims_lost"`
}

// ExecutorState is an executor's live, in-memory state: executor.describe's
// answer, and (without running) executor.report's data.
type ExecutorState struct {
	ID             string `json:"id"`
	UptimeMS       int64  `json:"uptime_ms"`
	MaxConcurrency int    `json:"max_concurrency"`
	InFlight       int    `json:"in_flight"`
	// On executor.describe and hosted reports, [] when nothing runs; omitted from
	// executor.report.
	Running *[]RunningActivity `json:"running,omitempty"`
	// How long the latest activity waited to start after it was due.
	ClaimLagMS        int64            `json:"claim_lag_ms"`
	HeartbeatFailures int64            `json:"heartbeat_failures"`
	Draining          bool             `json:"draining"`
	Counters          ExecutorCounters `json:"counters"`
}

// ExecutorReport is a hosted worker's heartbeat to the data plane (PUT
// /v1/executors/{id}, with the store key; see the storage protocol): its
// hello's sdk and executor, and its state with running.
type ExecutorReport struct {
	SDK      SDKInfo       `json:"sdk"`
	Executor ExecutorInfo  `json:"executor"`
	State    ExecutorState `json:"state"`
}
