// Code generated by runnerq-spec tools/gen from protocol/storage/executor_report.schema.json. DO NOT EDIT.

package protocol

// ExecutorReport is a worker's heartbeat (PUT /v1/executors/{id}, with the
// store key) for RunnerQ Cloud's Fleet, in a conductor agent's shapes: its
// hello's sdk and executor, and its executor.report state.
type ExecutorReport struct {
	SDK      SDKInfo       `json:"sdk"`
	Executor ExecutorInfo  `json:"executor"`
	State    ExecutorState `json:"state"`
}

type SDKInfo struct {
	Name     string `json:"name"`
	Version  string `json:"version"`
	Language string `json:"language"`
}

// ExecutorInfo is who the executor is.
type ExecutorInfo struct {
	// Stable for the process.
	ID       string `json:"id"`
	Hostname string `json:"hostname,omitempty"`
	// Exactly one, on the data plane.
	Queues         []string          `json:"queues,omitempty"`
	ActivityTypes  []string          `json:"activity_types,omitempty"`
	MaxConcurrency int               `json:"max_concurrency,omitempty"`
	StartedAt      string            `json:"started_at,omitempty"`
	Labels         map[string]string `json:"labels,omitempty"`
}

type ExecutorState struct {
	// Empty or the executor's id.
	ID                string            `json:"id"`
	UptimeMS          int64             `json:"uptime_ms"`
	MaxConcurrency    int               `json:"max_concurrency"`
	InFlight          int               `json:"in_flight"`
	Running           []RunningActivity `json:"running,omitempty"`
	ClaimLagMS        int64             `json:"claim_lag_ms"`
	HeartbeatFailures uint64            `json:"heartbeat_failures"`
	Draining          bool              `json:"draining"`
	Counters          *Counters         `json:"counters,omitempty"`
}

type RunningActivity struct {
	ActivityID string `json:"activity_id"`
	Type       string `json:"type"`
	Attempt    int    `json:"attempt"`
	StartedAt  string `json:"started_at"`
}

// Counters is activity outcomes since the executor started.
type Counters struct {
	Claimed      uint64 `json:"claimed"`
	Succeeded    uint64 `json:"succeeded"`
	Retried      uint64 `json:"retried"`
	Failed       uint64 `json:"failed"`
	TimedOut     uint64 `json:"timed_out"`
	DeadLettered uint64 `json:"dead_lettered"`
	ClaimsLost   uint64 `json:"claims_lost"`
}
