// Code generated by runnerq-spec tools/gen from protocol/storage/storage.schema.json. DO NOT EDIT.

package protocol

import (
	"encoding/json"
	"github.com/alob-mtc/runnerq-go/storage"
	"github.com/google/uuid"
	"time"
)

// Version is the RunnerQ-Storage-Version header's value.
const Version = "1"

// GetResultArgs are GetResult's arguments.
type GetResultArgs struct {
	ActivityID uuid.UUID `json:"activityID"`
}

// EnqueueArgs are Enqueue's arguments.
type EnqueueArgs struct {
	Activity storage.QueuedActivity `json:"activity"`
}

// DequeueArgs are Dequeue's arguments.
type DequeueArgs struct {
	WorkerID      string        `json:"workerID"`
	Timeout       time.Duration `json:"timeout"`
	ActivityTypes []string      `json:"activityTypes"`
}

// AckSuccessArgs are AckSuccess's arguments.
type AckSuccessArgs struct {
	ActivityID uuid.UUID       `json:"activityID"`
	Result     json.RawMessage `json:"result"`
	WorkerID   string          `json:"workerID"`
}

// AckFailureArgs are AckFailure's arguments.
type AckFailureArgs struct {
	ActivityID uuid.UUID           `json:"activityID"`
	Failure    storage.FailureKind `json:"failure"`
	WorkerID   string              `json:"workerID"`
}

// ProcessScheduledArgs are ProcessScheduled's arguments.
type ProcessScheduledArgs struct{}

// RequeueExpiredArgs are RequeueExpired's arguments.
type RequeueExpiredArgs struct {
	BatchSize int `json:"batchSize"`
}

// YieldArgs are Yield's arguments.
type YieldArgs struct {
	ActivityID uuid.UUID `json:"activityID"`
	WakeAt     time.Time `json:"wakeAt"`
	WorkerID   string    `json:"workerID"`
	Kind       string    `json:"kind"`
	Step       string    `json:"step"`
}

// ExtendLeaseArgs are ExtendLease's arguments.
type ExtendLeaseArgs struct {
	ActivityID uuid.UUID     `json:"activityID"`
	ExtendBy   time.Duration `json:"extendBy"`
}

// StoreResultArgs are StoreResult's arguments.
type StoreResultArgs struct {
	ActivityID      uuid.UUID              `json:"activityID"`
	OwnerActivityID uuid.UUID              `json:"ownerActivityID"`
	Result          storage.ActivityResult `json:"result"`
	Step            string                 `json:"step"`
}

// WakeWaitingArgs are WakeWaiting's arguments.
type WakeWaitingArgs struct {
	ActivityID uuid.UUID `json:"activityID"`
}

// SignalActivityArgs are SignalActivity's arguments.
type SignalActivityArgs struct {
	ActivityID uuid.UUID       `json:"activityID"`
	SignalID   uuid.UUID       `json:"signalID"`
	Name       string          `json:"name"`
	Payload    json.RawMessage `json:"payload"`
}

// LookupIdempotencyActivityIDArgs are LookupIdempotencyActivityID's arguments.
type LookupIdempotencyActivityIDArgs struct {
	IdempotencyKey string `json:"idempotencyKey"`
}

// CleanupExpiredArgs are CleanupExpired's arguments.
type CleanupExpiredArgs struct {
	Policy    storage.RetentionPolicy `json:"policy"`
	BatchSize int                     `json:"batchSize"`
}

// EnqueueIdempotentArgs are EnqueueIdempotent's arguments.
type EnqueueIdempotentArgs struct {
	Activity *storage.QueuedActivity `json:"activity"`
}

// RecordSpawnLinkedArgs are RecordSpawnLinked's arguments.
type RecordSpawnLinkedArgs struct {
	ChildID  uuid.UUID `json:"childID"`
	ParentID uuid.UUID `json:"parentID"`
}

// GetActivityArgs are GetActivity's arguments.
type GetActivityArgs struct {
	ActivityID uuid.UUID `json:"activityID"`
}

// GetActivityEventsArgs are GetActivityEvents's arguments.
type GetActivityEventsArgs struct {
	ActivityID uuid.UUID `json:"activityID"`
	Limit      int       `json:"limit"`
}

// GetActivityStepsArgs are GetActivitySteps's arguments.
type GetActivityStepsArgs struct {
	OwnerActivityID uuid.UUID `json:"ownerActivityID"`
}

// GetChildrenArgs are GetChildren's arguments.
type GetChildrenArgs struct {
	ParentID uuid.UUID `json:"parentID"`
	Offset   int       `json:"offset"`
	Limit    int       `json:"limit"`
}

// GetSubtreeArgs are GetSubtree's arguments.
type GetSubtreeArgs struct {
	RootID uuid.UUID `json:"rootID"`
}

// ListDeadLetterArgs are ListDeadLetter's arguments.
type ListDeadLetterArgs struct {
	Offset int `json:"offset"`
	Limit  int `json:"limit"`
}

// DequeueBatchArgs are DequeueBatch's arguments.
type DequeueBatchArgs struct {
	WorkerIDPrefix string        `json:"workerIDPrefix"`
	Limit          int           `json:"limit"`
	Timeout        time.Duration `json:"timeout"`
	ActivityTypes  []string      `json:"activityTypes"`
}

// ExtendLeaseForWorkerArgs are ExtendLeaseForWorker's arguments.
type ExtendLeaseForWorkerArgs struct {
	ActivityID uuid.UUID     `json:"activityID"`
	WorkerID   string        `json:"workerID"`
	ExtendBy   time.Duration `json:"extendBy"`
}

// StoreCheckpointArgs are StoreCheckpoint's arguments.
type StoreCheckpointArgs struct {
	ResultID uuid.UUID              `json:"resultID"`
	OwnerID  uuid.UUID              `json:"ownerID"`
	WorkerID string                 `json:"workerID"`
	Result   storage.ActivityResult `json:"result"`
	Step     string                 `json:"step"`
}

// EnqueueForWorkerArgs are EnqueueForWorker's arguments.
type EnqueueForWorkerArgs struct {
	A        storage.QueuedActivity `json:"a"`
	OwnerID  uuid.UUID              `json:"ownerID"`
	WorkerID string                 `json:"workerID"`
}

// EnqueueIdempotentForWorkerArgs are EnqueueIdempotentForWorker's arguments.
type EnqueueIdempotentForWorkerArgs struct {
	A        *storage.QueuedActivity `json:"a"`
	OwnerID  uuid.UUID               `json:"ownerID"`
	WorkerID string                  `json:"workerID"`
}

// RegisterDependencyArgs are RegisterDependency's arguments.
type RegisterDependencyArgs struct {
	WaiterID uuid.UUID `json:"waiterID"`
	ResultID uuid.UUID `json:"resultID"`
	WorkerID string    `json:"workerID"`
}

// YieldForResultArgs are YieldForResult's arguments.
type YieldForResultArgs struct {
	WaiterID   uuid.UUID  `json:"waiterID"`
	ResultID   uuid.UUID  `json:"resultID"`
	ProducerID *uuid.UUID `json:"producerID"`
	WakeAt     time.Time  `json:"wakeAt"`
	WorkerID   string     `json:"workerID"`
	Kind       string     `json:"kind"`
	Step       string     `json:"step"`
}

// DequeueBatchEncodedArgs are DequeueBatchEncoded's arguments.
type DequeueBatchEncodedArgs struct {
	WorkerIDPrefix string        `json:"workerIDPrefix"`
	Limit          int           `json:"limit"`
	Timeout        time.Duration `json:"timeout"`
	ActivityTypes  []string      `json:"activityTypes"`
	Serializations []string      `json:"serializations"`
}

// AckSuccessEncodedArgs are AckSuccessEncoded's arguments.
type AckSuccessEncodedArgs struct {
	ActivityID    uuid.UUID       `json:"activityID"`
	Result        json.RawMessage `json:"result"`
	Serialization string          `json:"serialization"`
	WorkerID      string          `json:"workerID"`
}

// SignalActivityEncodedArgs are SignalActivityEncoded's arguments.
type SignalActivityEncodedArgs struct {
	ActivityID    uuid.UUID       `json:"activityID"`
	SignalID      uuid.UUID       `json:"signalID"`
	Name          string          `json:"name"`
	Payload       json.RawMessage `json:"payload"`
	Serialization string          `json:"serialization"`
}

// NewArgs returns a pointer to a new zero value of operation's arguments,
// or nil for an unknown operation.
func NewArgs(operation string) any {
	switch operation {
	case "GetResult":
		return new(GetResultArgs)
	case "Enqueue":
		return new(EnqueueArgs)
	case "Dequeue":
		return new(DequeueArgs)
	case "AckSuccess":
		return new(AckSuccessArgs)
	case "AckFailure":
		return new(AckFailureArgs)
	case "ProcessScheduled":
		return new(ProcessScheduledArgs)
	case "RequeueExpired":
		return new(RequeueExpiredArgs)
	case "Yield":
		return new(YieldArgs)
	case "ExtendLease":
		return new(ExtendLeaseArgs)
	case "StoreResult":
		return new(StoreResultArgs)
	case "WakeWaiting":
		return new(WakeWaitingArgs)
	case "SignalActivity":
		return new(SignalActivityArgs)
	case "LookupIdempotencyActivityID":
		return new(LookupIdempotencyActivityIDArgs)
	case "CleanupExpired":
		return new(CleanupExpiredArgs)
	case "EnqueueIdempotent":
		return new(EnqueueIdempotentArgs)
	case "RecordSpawnLinked":
		return new(RecordSpawnLinkedArgs)
	case "GetActivity":
		return new(GetActivityArgs)
	case "GetActivityEvents":
		return new(GetActivityEventsArgs)
	case "GetActivitySteps":
		return new(GetActivityStepsArgs)
	case "GetChildren":
		return new(GetChildrenArgs)
	case "GetSubtree":
		return new(GetSubtreeArgs)
	case "ListDeadLetter":
		return new(ListDeadLetterArgs)
	case "DequeueBatch":
		return new(DequeueBatchArgs)
	case "ExtendLeaseForWorker":
		return new(ExtendLeaseForWorkerArgs)
	case "StoreCheckpoint":
		return new(StoreCheckpointArgs)
	case "EnqueueForWorker":
		return new(EnqueueForWorkerArgs)
	case "EnqueueIdempotentForWorker":
		return new(EnqueueIdempotentForWorkerArgs)
	case "RegisterDependency":
		return new(RegisterDependencyArgs)
	case "YieldForResult":
		return new(YieldForResultArgs)
	case "DequeueBatchEncoded":
		return new(DequeueBatchEncodedArgs)
	case "AckSuccessEncoded":
		return new(AckSuccessEncodedArgs)
	case "SignalActivityEncoded":
		return new(SignalActivityEncodedArgs)
	case "WaitForResult":
		return new(GetResultArgs)
	}
	return nil
}

// ErrorCodes are the wire codes of the storage error kinds, indexed by kind
// number (storage.StorageErrorKind).
var ErrorCodes = [...]string{
	"unavailable",
	"conflict",
	"not_found",
	"internal",
	"serialization",
	"configuration",
	"timeout",
	"duplicate_activity",
	"idempotency_conflict",
	"claim_lost",
	"checkpoint_conflict",
	"invalid_argument",
	"unsupported",
}
